Repository PCextreme/cloudstack-php, pull requests merged in 2018-10, with the labels that each got.

#8 Implemented Infection as Mutation testing framework
  .travis.yml
  composer.json
  infection.json.dist
Labels: enhancement

#6 Enforced stricter coding standards, and did small fixes
  .travis.yml
  composer.json
  phpcs.ruleset.xml
  src/AbstractClient.php
  src/Client.php
  src/Console/ApiListCommand.php
  src/Console/Application.php
  src/Exception/ClientException.php
  src/RequestFactory.php
  src/Util/UrlHelpersTrait.php
Labels: enhancement

#18 Stricter Typing
  src/AbstractClient.php
  src/Client.php
  src/Console/ApiListCommand.php
  src/Console/Application.php
  src/Exception/ClientException.php
  src/RequestFactory.php
  src/Util/UrlHelpersTrait.php
  test/src/AbstractClientTest.php
Labels: Hacktoberfest

#25 Fix php requirement in readme
  README.md
Labels: Hacktoberfest

#22 Eliminate risks
  src/Client.php
  test/src/AbstractClientTest.php
  test/src/ClientTest.php
  test/src/TestCase.php
Labels: Hacktoberfest

#26 Disabled identical-equal and not-identical-not-equal mutators
  infection.json.dist
Labels: Hacktoberfest

#29 Fixed coveralls binary name in travis.yml
  .travis.yml
Labels: Bug

#28 Transformed api-list caching system
  bin/cloudstack
  cache/0/F/3RtksEgOFgMXXmCzBgDM
  cache/api_list.php
  composer.json
  src/Client.php
  src/Console/ApiListCommand.php
  test/src/Console/ApiListCommandTest.php
Labels: Hacktoberfest

#20 Contributing + Makefile
  .travis.yml
  CONTRIBUTING.md
  Makefile
  README.md
  composer.json
Labels: Hacktoberfest
